### ISSUE TITLE
qri.get().readme only returning Readme("")

### ISSUE THREAD

**Issue by xxristoskk** [qri-io/qri-python#16]
Running `qri.get('xristosk/bot_sentinel_trolls').readme` is returning `Readme("")`

Same happens with other datasets I have locally.

**Comment by dustmop** [comment]
Fixed by e92bd6f544ebd0f7adcf421ec9fb3882455c9345. You can now do: `qri.get('me/my_ds').readme.script` to get the markdown text, and `qri.get('me/my_ds').readme.render()` to see the rendered html. The readme itself will render depending upon the environment its running in: markdown for console, html for jupyter.

This is working in the development version, but now in the pip release, as other issues are blocking a new release.
